apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name}}-fluentbit
  labels: {{ include "logging.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name}}-fluentbit
  labels: {{ include "logging.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name}}-fluentbit
  labels: {{ include "logging.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name}}-fluentbit
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name}}-fluentbit
  namespace: {{ .Release.Namespace }}