apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: logging
  namespace: {{ .Release.Namespace }}
value: 500
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: logging-data
  namespace: {{ .Release.Namespace }}
value: 1000
