{{- if .Values.kafka.enabled }}
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ .Release.Name }}-topics-config
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/check_host_port.sh $kafka 9092"]
        env:
          - name: kafka
            value: {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}
        volumeMounts:
        - mountPath: "/init"
          name: init
      containers:
      - name: kafka-topic-config
        image: {{ .Values.kafka.image }}:{{ .Values.kafka.imageTag }}
        command: ["/bin/sh","-c","{{- range .Values.kafka.topics.name -}} /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server $kafka --create  --topic {{ . }} \
          --partitions {{ ($.Values.kafka.replicas | int) }} \
          --replication-factor {{ (sub ($.Values.kafka.replicas | int) 1) }} \
          --if-not-exists && {{ end -}}
        {{- range .Values.kafka.topics.name -}} /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server $kafka  --alter  \
          --topic {{ . }} --partitions {{ ($.Values.kafka.replicas | int) }} \
          --if-exists || true && {{ end -}}
        {{- range .Values.kafka.topics.name -}} /opt/kafka/bin/kafka-configs.sh \
          --bootstrap-server $kafka  --alter \
          --entity-type topics --entity-name {{ . }} \
          --add-config {{ $.Values.kafka.topics.config }} && {{ end -}} true"]        
        env:
        - name: kafka
          value: {{$.Release.Name}}-kafka-0:9092 
      restartPolicy: Never
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755  
{{- end }}           
