{{- if .Values.kafka.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  ports:
  - port: 2181
    name: client
  - port: 7070
    name: metrics  
  - port: 8080
    name: admin  
  - port: 9191
    name: exporter
  selector: {{ include "logging.selectorLabels" . | indent 4 }}
    type: zk

{{ range $zkId := until (.Values.zookeeper.replicas | int) }}    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-zk-{{ $zkId }}
  labels: {{ include "logging.labels" $ | indent 4 }}
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: peer
    - port: 3888
      name: leader
    - port: 8080
      name: admin  
  selector: {{ include "logging.selectorLabels" $ | indent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-zk-{{ $zkId }}
    type: zk    
{{- end }}
{{- end }}    